"""create_base_tables

Revision ID: c732fb5ac39c
Revises: 
Create Date: 2026-07-09 12:16:17.017237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c732fb5ac39c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension for vector embeddings
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arc_definitions',
    sa.Column('arc_type', sa.Enum('RISE_AND_OVEREXTENSION', 'HUBRIS_NEMESIS', 'REFORM_THEN_REACTION', 'DECADENCE_AND_RENEWAL', 'SIEGE_AND_COLLAPSE', 'SUCCESSION_CRISIS', 'CREDIT_BOOM_AND_BUST', 'GENERATIONAL_FORGETTING', 'HERO_JOURNEY', 'TRAGEDY', 'COMEDY', 'REBIRTH', 'VOYAGE_RETURN', 'RAGS_TO_RICHES', name='arctype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.Column('phase_descriptions', sa.JSON(), nullable=False),
    sa.Column('typical_duration', sa.String(length=100), nullable=True),
    sa.Column('transition_tendencies', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('arc_type')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scale', sa.Enum('CIVILIZATIONAL', 'INSTITUTIONAL', 'GENERATIONAL', 'EPISODIC', name='cyclescale'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_cycle_id', sa.UUID(), nullable=True),
    sa.Column('dominant_arc_types', sa.JSON(), nullable=False),
    sa.Column('phase_estimate', sa.Enum('SETUP', 'RISING_ACTION', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', 'BOOM', 'EUPHORIA', 'DISTRESS', 'PANIC', 'REVULSION', name='arcphase'), nullable=True),
    sa.Column('framework_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_cycle_id'], ['cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cycles_parent_id', 'cycles', ['parent_cycle_id'], unique=False)
    op.create_index('ix_cycles_scale', 'cycles', ['scale'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_precision', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('setting_description', sa.Text(), nullable=True),
    sa.Column('initiating_conditions', sa.JSON(), nullable=False),
    sa.Column('escalation_mechanics', sa.JSON(), nullable=False),
    sa.Column('tension', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('consequences', sa.JSON(), nullable=False),
    sa.Column('arc_type', sa.Enum('RISE_AND_OVEREXTENSION', 'HUBRIS_NEMESIS', 'REFORM_THEN_REACTION', 'DECADENCE_AND_RENEWAL', 'SIEGE_AND_COLLAPSE', 'SUCCESSION_CRISIS', 'CREDIT_BOOM_AND_BUST', 'GENERATIONAL_FORGETTING', 'HERO_JOURNEY', 'TRAGEDY', 'COMEDY', 'REBIRTH', 'VOYAGE_RETURN', 'RAGS_TO_RICHES', name='arctype'), nullable=True),
    sa.Column('arc_phase', sa.Enum('SETUP', 'RISING_ACTION', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', 'BOOM', 'EUPHORIA', 'DISTRESS', 'PANIC', 'REVULSION', name='arcphase'), nullable=True),
    sa.Column('phase_confidence', sa.Float(), nullable=False),
    sa.Column('arc_rationale', sa.Text(), nullable=True),
    sa.Column('secondary_arcs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extracted_from', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episodes_arc_phase', 'episodes', ['arc_phase'], unique=False)
    op.create_index('ix_episodes_arc_type', 'episodes', ['arc_type'], unique=False)
    op.create_index('ix_episodes_embedding', 'episodes', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('ix_episodes_start_date', 'episodes', ['start_date'], unique=False)
    op.create_table('extraction_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=255), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_records_source_chunk_id'), 'extraction_records', ['source_chunk_id'], unique=False)
    op.create_table('theses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analog_episode_ids', sa.JSON(), nullable=False),
    sa.Column('analog_similarity_scores', sa.JSON(), nullable=False),
    sa.Column('dominant_continuation', sa.Text(), nullable=False),
    sa.Column('alternative_continuations', sa.JSON(), nullable=False),
    sa.Column('watch_for_indicators', sa.JSON(), nullable=False),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=100), nullable=True),
    sa.Column('resolution_criteria', sa.JSON(), nullable=False),
    sa.Column('cited_episodes', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_outcome', sa.String(length=50), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_theses_created_at', 'theses', ['created_at'], unique=False)
    op.create_index('ix_theses_resolved', 'theses', ['resolved'], unique=False)
    op.create_table('cycle_episode_association',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cycle_id', 'episode_id')
    )
    op.create_table('episode_actor_association',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'actor_id')
    )
    op.create_table('source_passages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.String(length=255), nullable=False),
    sa.Column('passage_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('historiographic_school', sa.String(length=100), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_passages_work_id'), 'source_passages', ['work_id'], unique=False)
    op.create_index('ix_source_passages_work_passage', 'source_passages', ['work_id', 'passage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_passages_work_passage', table_name='source_passages')
    op.drop_index(op.f('ix_source_passages_work_id'), table_name='source_passages')
    op.drop_table('source_passages')
    op.drop_table('episode_actor_association')
    op.drop_table('cycle_episode_association')
    op.drop_index('ix_theses_resolved', table_name='theses')
    op.drop_index('ix_theses_created_at', table_name='theses')
    op.drop_table('theses')
    op.drop_index(op.f('ix_extraction_records_source_chunk_id'), table_name='extraction_records')
    op.drop_table('extraction_records')
    op.drop_index('ix_episodes_start_date', table_name='episodes')
    op.drop_index('ix_episodes_embedding', table_name='episodes', postgresql_using='ivfflat')
    op.drop_index('ix_episodes_arc_type', table_name='episodes')
    op.drop_index('ix_episodes_arc_phase', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_cycles_scale', table_name='cycles')
    op.drop_index('ix_cycles_parent_id', table_name='cycles')
    op.drop_table('cycles')
    op.drop_table('arc_definitions')
    op.drop_table('actors')
    # ### end Alembic commands ###
